### ISSUE TITLE
KDE taskbar

### ISSUE THREAD

**Issue by sanenr9** [stockmind/gpd-pocket-screen-indicator#3]
Hello,

is there an option to get this also running in KDE?

I see explanations for unity and Gnome, but i am using KDE. Sometimes the touchscreen stops to function and the mouse seems to be permanently left pressed after opening the gpd pocket. the only chance right now for me is to reboot the device.

I installed your package but there does not seem to be an easy way to get the touchscreen reactivation active for kde.

Can this be fired via commandline?

Thanks,

Michael

**Comment by stockmind** [comment]
Do you see the tray icon in KDE? On my test it should work but it's possibile that you get a different icon like a Gear or something. 

Try to run

    gpdscreen-indicator


To force open the tray icon.
Or try

    gpdscreen touchreset

To reset touchscreen.

Your issue is odd, can you also run the script referenced in "Problem reporting" section and post output? This will help me debug, Thanks!

**Comment by sanenr9** [comment]
Hi,
when i run gpdscreen-indicator i get:

```
Traceback (most recent call last):
  File "/usr/local/sbin/gpdscreen-indicator", line 19, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 118, in require_version         
    raise ValueError('Namespace %s not available' % namespace)                                 
ValueError: Namespace AppIndicator3 not available  
```

Here the data from your problem-reporting.sh 
```
**Kernel:** 4.13.0-rc5-custom
**Desktop Environment:** 
**Display:** :0
**Monitor:** DSI1 connected primary 1920x1200+0+0 right (normal left inverted right x axis y axis) 95mm x 151mm
**Scripts:**  gpdfand gpdscreen gpdscreen-indicator
**EFI:**  [ 0.000000] efi: EFI v2.40 by American Megatrends
**EFI**  Release Date: 06/28/2017
```

**Comment by stockmind** [comment]
Check dependencies section. You are missing appindicator dep

sudo apt install gir1.2-appindicator3-0.1


Il 19 set 2017 18:49, "sanenr9" <notifications@github.com> ha scritto:

Hi,
when i run gpdscreen-indicator i get:

Traceback (most recent call last):
  File "/usr/local/sbin/gpdscreen-indicator", line 19, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 118, in
require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

Here the data from your problem-reporting.sh
**Kernel:** 4.13.0-rc5-custom **Desktop Environment:** **Display:** :0
**Monitor:** DSI1 connected primary 1920x1200+0+0 right (normal left
inverted right x axis y axis) 95mm x 151mm **Scripts:** gpdfand gpdscreen
gpdscreen-indicator **EFI:** [ 0.000000] efi: EFI v2.40 by American
Megatrends **EFI** Release Date: 06/28/2017

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/stockmind/gpd-pocket-screen-indicator/issues/3#issuecomment-330601652>,
or mute the thread

**Comment by sanenr9** [comment]
Thanks for your help, now i see the icon.

Sorry for causing work, thanks again!!!
